/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.GithubLinks;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GithubLinksRecord extends UpdatableRecordImpl<GithubLinksRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached GithubLinksRecord
     */
    public GithubLinksRecord() {
        super(GithubLinks.GITHUB_LINKS);
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    @ConstructorProperties({"id", "linkId", "branchCount"})
    public GithubLinksRecord(@Nullable Long id, @NotNull Long linkId, @NotNull Long branchCount) {
        super(GithubLinks.GITHUB_LINKS);

        setId(id);
        setLinkId(linkId);
        setBranchCount(branchCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubLinksRecord
     */
    public GithubLinksRecord(edu.java.domain.jooq.tables.pojos.GithubLinks value) {
        super(GithubLinks.GITHUB_LINKS);

        if (value != null) {
            setId(value.getId());
            setLinkId(value.getLinkId());
            setBranchCount(value.getBranchCount());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>GITHUB_LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>GITHUB_LINKS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>GITHUB_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>GITHUB_LINKS.BRANCH_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getBranchCount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>GITHUB_LINKS.BRANCH_COUNT</code>.
     */
    public void setBranchCount(@NotNull Long value) {
        set(2, value);
    }

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return GithubLinks.GITHUB_LINKS.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return GithubLinks.GITHUB_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return GithubLinks.GITHUB_LINKS.BRANCH_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component3() {
        return getBranchCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value3() {
        return getBranchCount();
    }

    @Override
    @NotNull
    public GithubLinksRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public GithubLinksRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord value3(@NotNull Long value) {
        setBranchCount(value);
        return this;
    }

    @Override
    @NotNull
    public GithubLinksRecord values(@Nullable Long value1, @NotNull Long value2, @NotNull Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
