/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.StackoverflowLinks;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowLinksRecord extends UpdatableRecordImpl<StackoverflowLinksRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINKS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@NotNull Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINKS.ANSWER_COUNT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getAnswerCount() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return StackoverflowLinks.STACKOVERFLOW_LINKS.ANSWER_COUNT;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long component3() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value3() {
        return getAnswerCount();
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord value3(@NotNull Long value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public StackoverflowLinksRecord values(@Nullable Long value1, @NotNull Long value2, @NotNull Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StackoverflowLinksRecord
     */
    public StackoverflowLinksRecord() {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);
    }

    /**
     * Create a detached, initialised StackoverflowLinksRecord
     */
    @ConstructorProperties({ "id", "linkId", "answerCount" })
    public StackoverflowLinksRecord(@Nullable Long id, @NotNull Long linkId, @NotNull Long answerCount) {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);

        setId(id);
        setLinkId(linkId);
        setAnswerCount(answerCount);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised StackoverflowLinksRecord
     */
    public StackoverflowLinksRecord(edu.java.domain.jooq.tables.pojos.StackoverflowLinks value) {
        super(StackoverflowLinks.STACKOVERFLOW_LINKS);

        if (value != null) {
            setId(value.getId());
            setLinkId(value.getLinkId());
            setAnswerCount(value.getAnswerCount());
            resetChangedOnNotNull();
        }
    }
}
