global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'scrapper'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: "scrapper"
  - job_name: 'bot'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8190']
        labels:
          application: "bot"
