app:
  telegram-token: ${TOKEN}
  client:
    tgChatClient:
      base-url: "http://localhost:8080/TgChatClient"
    linksClient:
      base-url: "http://localhost:8080/links"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml


springdoc:
  swagger-ui:
    path: /swagger-ui
