app:
  telegram-token: 6590963871:AAGq-D_-i_R3ds4fpivmSfLldOywh_73bFY
  client:
    tg-—Åhat:
      base-url: "http://localhost:8080/tg-chat"
    links:
      base-url: "http://localhost:8080/links"
  retry-config:
    policy: constant
    max-attempts: 5
    backoff: 2s
    maxBackoff:
    statusCodes:
      - 400
      - 500
      - 403
      - 501
      - 502
    jitter: 0.75

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml


springdoc:
  swagger-ui:
    path: /swagger-ui
