/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TgChatLinks implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long tgChatId;
    private Long linkId;

    public TgChatLinks() {
    }

    public TgChatLinks(TgChatLinks value) {
        this.id = value.id;
        this.tgChatId = value.tgChatId;
        this.linkId = value.linkId;
    }

    @ConstructorProperties({"id", "tgChatId", "linkId"})
    public TgChatLinks(
        @Nullable Long id,
        @NotNull Long tgChatId,
        @NotNull Long linkId
    ) {
        this.id = id;
        this.tgChatId = tgChatId;
        this.linkId = linkId;
    }

    /**
     * Getter for <code>TG_CHAT_LINKS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>TG_CHAT_LINKS.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>TG_CHAT_LINKS.TG_CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChatId() {
        return this.tgChatId;
    }

    /**
     * Setter for <code>TG_CHAT_LINKS.TG_CHAT_ID</code>.
     */
    public void setTgChatId(@NotNull Long tgChatId) {
        this.tgChatId = tgChatId;
    }

    /**
     * Getter for <code>TG_CHAT_LINKS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>TG_CHAT_LINKS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TgChatLinks other = (TgChatLinks) obj;
        if (this.id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!this.id.equals(other.id)) {
            return false;
        }
        if (this.tgChatId == null) {
            if (other.tgChatId != null) {
                return false;
            }
        } else if (!this.tgChatId.equals(other.tgChatId)) {
            return false;
        }
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.tgChatId == null) ? 0 : this.tgChatId.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TgChatLinks (");

        sb.append(id);
        sb.append(", ").append(tgChatId);
        sb.append(", ").append(linkId);

        sb.append(")");
        return sb.toString();
    }
}
