/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.GithubLinks;
import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.StackoverflowLinks;
import edu.java.domain.jooq.tables.TgChatLinks;
import edu.java.domain.jooq.tables.TgChats;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>GITHUB_LINKS</code>.
     */
    public final GithubLinks GITHUB_LINKS = GithubLinks.GITHUB_LINKS;

    /**
     * The table <code>LINKS</code>.
     */
    public final Links LINKS = Links.LINKS;

    /**
     * The table <code>STACKOVERFLOW_LINKS</code>.
     */
    public final StackoverflowLinks STACKOVERFLOW_LINKS = StackoverflowLinks.STACKOVERFLOW_LINKS;

    /**
     * The table <code>TG_CHAT_LINKS</code>.
     */
    public final TgChatLinks TG_CHAT_LINKS = TgChatLinks.TG_CHAT_LINKS;

    /**
     * The table <code>TG_CHATS</code>.
     */
    public final TgChats TG_CHATS = TgChats.TG_CHATS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    @NotNull
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    @NotNull
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            GithubLinks.GITHUB_LINKS,
            Links.LINKS,
            StackoverflowLinks.STACKOVERFLOW_LINKS,
            TgChatLinks.TG_CHAT_LINKS,
            TgChats.TG_CHATS
        );
    }
}
